# Minimum players required before the fishing event can start
minimum-players: 2

# Define points for each fish type
fish-points:
  COD: 1
  SALMON: 2
  TROPICAL_FISH: 3
  PUFFERFISH: 5

# Prize system
prizes:
  enabled: true
  # One command per leaderboard placement (1st = first command, 2nd = second, etc.)
  # Placeholders:
  #   <player> = player name
  #   <points> = total score
  #   <fish>   = total fish caught
  commands:
    - "give <player> diamond 3"
    - "give <player> emerald 5"
    - "give <player> gold_ingot 10"
